[package]
name = "ip-tray"
version = "0.1.0"
edition = "2021"

[dependencies]
tao = "0.30"
tray-icon = "0.19"
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_NetworkManagement_IpHelper"] }
ureq ={ version = "2", default-features = false, features = ["tls"] }

[build-dependencies]
winresource = "0.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
